### ISSUE TITLE
Feature request: save commands between reboots and don't allow duplicate commands

### ISSUE THREAD

**Issue by justinhunt1223** [hugobloem/esp-ha-speech#13]
Thanks for the update to fix a handful of issues! I'm requesting commands be saved between reboots if possible. Also commands seem to be able to be added as duplicates (over mqtt) which causes random crashes for me.

**Comment by hugobloem** [comment]
Hi, I will look into deduplication soon. However, it should already save the commands between reboots after the latest commits.

**Comment by hugobloem** [comment]
Fixed duplication in [bbd6ee7](https://github.com/hugobloem/esp-ha-speech/commit/bbd6ee7c804448fad7dcd548c836a1dd595b1a3f)

**Comment by justinhunt1223** [comment]
Deduplication works, thanks! I'm still having issues with commands not saving on reboots. I've removed the default commands from `app_sr.c` and only add commands over mqtt. I've flashed with the latest changes as well.
